version: "3.9"
services:
  bot:
    image: "y2kot/visitor-bot:1.3"
    volumes:
      - ./data:/data
    deploy:
      restart_policy:
        condition: on-failure
        window: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "5mb"
        max-file: "5"

